#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        HMP4040.py
#
#  Project :     HMP4040
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      sergey.v.babenkov$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["HMP4040", "HMP4040Class", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(HMP4040.additionnal_import) ENABLED START -----#
from pylink import TCPLink
import time
from threading import RLock
import threading

import Tkinter as tk
import tkMessageBox
#----- PROTECTED REGION END -----#	//	HMP4040.additionnal_import

# Device States Description
# No states for this device


class HMP4040 (PyTango.Device_4Impl):
    """HMP4040"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(HMP4040.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	HMP4040.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        HMP4040.init_device(self)
        #----- PROTECTED REGION ID(HMP4040.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	HMP4040.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(HMP4040.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	HMP4040.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_CH1_V_read_read = 0.0
        self.attr_CH1_C_read_read = 0.0
        self.attr_CH2_V_read_read = 0.0
        self.attr_CH2_C_read_read = 0.0
        self.attr_CH3_V_read_read = 0.0
        self.attr_CH3_C_read_read = 0.0
        self.attr_CH4_V_read_read = 0.0
        self.attr_CH4_C_read_read = 0.0
        self.attr_output_on_off_read_read = False
        self.attr_output_CH1_read_read = False
        self.attr_output_CH2_read_read = False
        self.attr_output_CH3_read_read = False
        self.attr_output_CH4_read_read = False
        #----- PROTECTED REGION ID(HMP4040.init_device) ENABLED START -----#
        self.check_connection_warning=False
        self.connection_locked=False
        
        self.output_ch=[False]*5
        self.voltage=[0.0]*5
        self.current=[0.0]*5
        self.voltage_limit=[0.0]*5
        self.connect()
        if not 'AskQuestion' in dir(self):
            self.AskQuestion = threading.Thread(target=self.AskQuestion_thread)
            self.AskQuestion.setDaemon(True)
            self.AskQuestion.start()
        if not 'pool_values' in dir(self):
            self.pool_values = threading.Thread(target=self.pool_values_thread)
            self.pool_values.setDaemon(True)
            self.pool_values.start() 

        #----- PROTECTED REGION END -----#	//	HMP4040.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(HMP4040.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	HMP4040.always_executed_hook

    # -------------------------------------------------------------------------
    #    HMP4040 read/write attribute methods
    # -------------------------------------------------------------------------
    
    def write_CH1_V(self, attr):
        self.debug_stream("In write_CH1_V()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(HMP4040.CH1_V_write) ENABLED START -----#
        while self.connection_locked==True:
            time.sleep(0.001)
        else:
            self.connection_locked=True
            if self.get_state() == PyTango.DevState.ON:
                self.write('INST OUT{}'.format('1'))
                self.write('VOLT {}'.format(str(data)))
            self.connection_locked=False            
        #----- PROTECTED REGION END -----#	//	HMP4040.CH1_V_write
        
    def write_CH1_C(self, attr):
        self.debug_stream("In write_CH1_C()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(HMP4040.CH1_C_write) ENABLED START -----#
        while self.connection_locked==True:
            time.sleep(0.001)
        else:
            self.connection_locked=True
            if self.get_state() == PyTango.DevState.ON:
                self.write('INST OUT{}'.format('1'))
                self.write('CURR {}'.format(str(data)))
            self.connection_locked=False                 
        #----- PROTECTED REGION END -----#	//	HMP4040.CH1_C_write
        
    def write_CH2_V(self, attr):
        self.debug_stream("In write_CH2_V()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(HMP4040.CH2_V_write) ENABLED START -----#
        while self.connection_locked==True:
            time.sleep(0.001)
        else:
            self.connection_locked=True
            if self.get_state() == PyTango.DevState.ON:
                self.write('INST OUT{}'.format('2'))
                self.write('VOLT {}'.format(str(data)))
            self.connection_locked=False         
        #----- PROTECTED REGION END -----#	//	HMP4040.CH2_V_write
        
    def write_CH2_C(self, attr):
        self.debug_stream("In write_CH2_C()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(HMP4040.CH2_C_write) ENABLED START -----#
        while self.connection_locked==True:
            time.sleep(0.001)
        else:
            self.connection_locked=True
            if self.get_state() == PyTango.DevState.ON:
                self.write('INST OUT{}'.format('2'))
                self.write('CURR {}'.format(str(data)))
            self.connection_locked=False            
        #----- PROTECTED REGION END -----#	//	HMP4040.CH2_C_write
        
    def write_CH3_V(self, attr):
        self.debug_stream("In write_CH3_V()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(HMP4040.CH3_V_write) ENABLED START -----#
        while self.connection_locked==True:
            time.sleep(0.001)
        else:
            self.connection_locked=True
            if self.get_state() == PyTango.DevState.ON:
                self.write('INST OUT{}'.format('3'))
                self.write('VOLT {}'.format(str(data)))
            self.connection_locked=False            
        #----- PROTECTED REGION END -----#	//	HMP4040.CH3_V_write
        
    def write_CH3_C(self, attr):
        self.debug_stream("In write_CH3_C()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(HMP4040.CH3_C_write) ENABLED START -----#
        while self.connection_locked==True:
            time.sleep(0.001)
        else:
            self.connection_locked=True
            if self.get_state() == PyTango.DevState.ON:
                self.write('INST OUT{}'.format('3'))
                self.write('CURR {}'.format(str(data)))
            self.connection_locked=False         
        #----- PROTECTED REGION END -----#	//	HMP4040.CH3_C_write
        
    def write_CH4_V(self, attr):
        self.debug_stream("In write_CH4_V()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(HMP4040.CH4_V_write) ENABLED START -----#
        while self.connection_locked==True:
            time.sleep(0.001)
        else:
            self.connection_locked=True
            if self.get_state() == PyTango.DevState.ON:
                self.write('INST OUT{}'.format('4'))
                self.write('VOLT {}'.format(str(data)))
            self.connection_locked=False            
        #----- PROTECTED REGION END -----#	//	HMP4040.CH4_V_write
        
    def write_CH4_C(self, attr):
        self.debug_stream("In write_CH4_C()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(HMP4040.CH4_C_write) ENABLED START -----#
        while self.connection_locked==True:
            time.sleep(0.001)
        else:
            self.connection_locked=True
            if self.get_state() == PyTango.DevState.ON:
                self.write('INST OUT{}'.format('4'))
                self.write('CURR {}'.format(str(data)))
            self.connection_locked=False         
        #----- PROTECTED REGION END -----#	//	HMP4040.CH4_C_write
        
    def write_output_on_off(self, attr):
        self.debug_stream("In write_output_on_off()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(HMP4040.output_on_off_write) ENABLED START -----#
        while self.connection_locked==True:
            time.sleep(0.001)
        else:
            self.connection_locked=True
            if self.get_state() == PyTango.DevState.ON:
                if data==True:
                    self.write('OUTP:GEN {}'.format('1'))      
                else:
                    self.write('OUTP:GEN {}'.format('0'))
            self.connection_locked=False         
        #----- PROTECTED REGION END -----#	//	HMP4040.output_on_off_write
        
    def write_output_CH1(self, attr):
        self.debug_stream("In write_output_CH1()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(HMP4040.output_CH1_write) ENABLED START -----#
        while self.connection_locked==True:
            time.sleep(0.001)
        else:
            self.connection_locked=True
            if self.get_state() == PyTango.DevState.ON:
                if data==True:
                    self.write('INST OUT{}'.format('1'))
                    self.write('OUTP {}'.format("1"))            
                else:
                    self.write('INST OUT{}'.format('1'))
                    self.write('OUTP {}'.format('0'))
            self.connection_locked=False    
                
        #----- PROTECTED REGION END -----#	//	HMP4040.output_CH1_write
        
    def write_output_CH2(self, attr):
        self.debug_stream("In write_output_CH2()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(HMP4040.output_CH2_write) ENABLED START -----#
        while self.connection_locked==True:
            time.sleep(0.001)
        else:
            self.connection_locked=True
            if self.get_state() == PyTango.DevState.ON:
                if data==True:
                    self.write('INST OUT{}'.format('2'))
                    self.write('OUTP {}'.format("1"))            
                else:
                    self.write('INST OUT{}'.format('2'))
                    self.write('OUTP {}'.format('0'))
            self.connection_locked=False            
        #----- PROTECTED REGION END -----#	//	HMP4040.output_CH2_write
        
    def write_output_CH3(self, attr):
        self.debug_stream("In write_output_CH3()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(HMP4040.output_CH3_write) ENABLED START -----#
        while self.connection_locked==True:
            time.sleep(0.001)
        else:
            self.connection_locked=True
            if self.get_state() == PyTango.DevState.ON:
                if data==True:
                    self.write('INST OUT{}'.format('3'))
                    self.write('OUTP {}'.format("1"))            
                else:
                    self.write('INST OUT{}'.format('3'))
                    self.write('OUTP {}'.format('0'))
            self.connection_locked=False           
        #----- PROTECTED REGION END -----#	//	HMP4040.output_CH3_write
        
    def write_output_CH4(self, attr):
        self.debug_stream("In write_output_CH4()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(HMP4040.output_CH4_write) ENABLED START -----#
        while self.connection_locked==True:
            time.sleep(0.001)
        else:
            self.connection_locked=True
            if self.get_state() == PyTango.DevState.ON:
                if data==True:
                    self.write('INST OUT{}'.format('4'))
                    self.write('OUTP {}'.format("1"))            
                else:
                    self.write('INST OUT{}'.format('4'))
                    self.write('OUTP {}'.format('0'))
            self.connection_locked=False         
        #----- PROTECTED REGION END -----#	//	HMP4040.output_CH4_write
        
    def read_CH1_V_read(self, attr):
        self.debug_stream("In read_CH1_V_read()")
        #----- PROTECTED REGION ID(HMP4040.CH1_V_read_read) ENABLED START -----#
        self.attr_CH1_V_read_read=self.voltage[1]
        attr.set_value(self.attr_CH1_V_read_read)
        
        #----- PROTECTED REGION END -----#	//	HMP4040.CH1_V_read_read
        
    def read_CH1_C_read(self, attr):
        self.debug_stream("In read_CH1_C_read()")
        #----- PROTECTED REGION ID(HMP4040.CH1_C_read_read) ENABLED START -----#
        self.attr_CH1_C_read_read=self.current[1]
        attr.set_value(self.attr_CH1_C_read_read)
        
        #----- PROTECTED REGION END -----#	//	HMP4040.CH1_C_read_read
        
    def read_CH2_V_read(self, attr):
        self.debug_stream("In read_CH2_V_read()")
        #----- PROTECTED REGION ID(HMP4040.CH2_V_read_read) ENABLED START -----#
        self.attr_CH2_V_read_read=self.voltage[2]        
        attr.set_value(self.attr_CH2_V_read_read)
        
        #----- PROTECTED REGION END -----#	//	HMP4040.CH2_V_read_read
        
    def read_CH2_C_read(self, attr):
        self.debug_stream("In read_CH2_C_read()")
        #----- PROTECTED REGION ID(HMP4040.CH2_C_read_read) ENABLED START -----#
        self.attr_CH2_C_read_read=self.current[2]
        attr.set_value(self.attr_CH2_C_read_read)
        
        #----- PROTECTED REGION END -----#	//	HMP4040.CH2_C_read_read
        
    def read_CH3_V_read(self, attr):
        self.debug_stream("In read_CH3_V_read()")
        #----- PROTECTED REGION ID(HMP4040.CH3_V_read_read) ENABLED START -----#    
        self.attr_CH3_V_read_read=self.voltage[3]        
        attr.set_value(self.attr_CH3_V_read_read)
        
        #----- PROTECTED REGION END -----#	//	HMP4040.CH3_V_read_read
        
    def read_CH3_C_read(self, attr):
        self.debug_stream("In read_CH3_C_read()")
        #----- PROTECTED REGION ID(HMP4040.CH3_C_read_read) ENABLED START -----#
        self.attr_CH3_C_read_read=self.current[3]
        attr.set_value(self.attr_CH3_C_read_read)
        
        #----- PROTECTED REGION END -----#	//	HMP4040.CH3_C_read_read
        
    def read_CH4_V_read(self, attr):
        self.debug_stream("In read_CH4_V_read()")
        #----- PROTECTED REGION ID(HMP4040.CH4_V_read_read) ENABLED START -----#
        self.attr_CH4_V_read_read=self.voltage[4]
        attr.set_value(self.attr_CH4_V_read_read)
        
        #----- PROTECTED REGION END -----#	//	HMP4040.CH4_V_read_read
        
    def read_CH4_C_read(self, attr):
        self.debug_stream("In read_CH4_C_read()")
        #----- PROTECTED REGION ID(HMP4040.CH4_C_read_read) ENABLED START -----#
        self.attr_CH4_C_read_read=self.current[4]
        attr.set_value(self.attr_CH4_C_read_read)
        
        #----- PROTECTED REGION END -----#	//	HMP4040.CH4_C_read_read
        
    def read_output_on_off_read(self, attr):
        self.debug_stream("In read_output_on_off_read()")
        #----- PROTECTED REGION ID(HMP4040.output_on_off_read_read) ENABLED START -----#

        attr.set_value(self.attr_output_on_off_read_read)
        
        #----- PROTECTED REGION END -----#	//	HMP4040.output_on_off_read_read
        
    def read_output_CH1_read(self, attr):
        self.debug_stream("In read_output_CH1_read()")
        #----- PROTECTED REGION ID(HMP4040.output_CH1_read_read) ENABLED START -----#
        self.attr_output_CH1_read_read=self.output_ch[1]
        attr.set_value(self.attr_output_CH1_read_read)
        
        #----- PROTECTED REGION END -----#	//	HMP4040.output_CH1_read_read
        
    def read_output_CH2_read(self, attr):
        self.debug_stream("In read_output_CH2_read()")
        #----- PROTECTED REGION ID(HMP4040.output_CH2_read_read) ENABLED START -----#
        self.attr_output_CH2_read_read=self.output_ch[2]
        attr.set_value(self.attr_output_CH2_read_read)
        
        #----- PROTECTED REGION END -----#	//	HMP4040.output_CH2_read_read
        
    def read_output_CH3_read(self, attr):
        self.debug_stream("In read_output_CH3_read()")
        #----- PROTECTED REGION ID(HMP4040.output_CH3_read_read) ENABLED START -----#
        self.attr_output_CH2_read_read=self.output_ch[2]
        attr.set_value(self.attr_output_CH3_read_read)
        
        #----- PROTECTED REGION END -----#	//	HMP4040.output_CH3_read_read
        
    def read_output_CH4_read(self, attr):
        self.debug_stream("In read_output_CH4_read()")
        #----- PROTECTED REGION ID(HMP4040.output_CH4_read_read) ENABLED START -----#
        self.attr_output_CH2_read_read=self.output_ch[2]
        attr.set_value(self.attr_output_CH4_read_read)
        
        #----- PROTECTED REGION END -----#	//	HMP4040.output_CH4_read_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(HMP4040.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	HMP4040.read_attr_hardware


    # -------------------------------------------------------------------------
    #    HMP4040 command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(HMP4040.programmer_methods) ENABLED START -----#

    def connect(self):
        self.tcp = TCPLink(self.host, self.port)
        self.write("*IDN?")
        if self.read().split(",")[0]=="ROHDE&SCHWARZ":
            self.set_state(PyTango.DevState.ON)
        else:
            self.set_state(PyTango.DevState.FAULT)
            self.check_connection_warning=True
            
    def pool_values_thread(self):
        while True:
            if self.get_state() == PyTango.DevState.ON:
                time1=time.time()
                while self.connection_locked==True:
                    time.sleep(0.001)
                else:
                    self.connection_locked=True
                    if self.send_and_recieve('OUTP:GEN?')=='1':
                        self.attr_output_on_off_read_read=True
                    else:
                        self.attr_output_on_off_read_read=False
                    self.connection_locked=False
                time.sleep(0.002)
                print (time.time()-time1) 
                                    
                
                for i in range(1,5,1):               
                    while self.connection_locked==True:
                        time.sleep(0.001)
                    else:
                        self.connection_locked=True
                        self.write('INST OUT{:d}'.format(i))
                        if self.send_and_recieve('OUTP?')=='1':
                            self.output_ch[i]=True
                        else:
                            self.output_ch[i]=False
                        self.voltage[i]=float(self.send_and_recieve('MEAS:VOLT?'))
                        self.current[i]=float(self.send_and_recieve('MEAS:CURR?'))
                        self.connection_locked=False
                    time.sleep(0.005)
                    print (time.time()-time1) 

                    time.sleep(0.002)
                print (time.time()-time1)                        
            time.sleep(0.1)
        
        
    def reconnect(self):
        self.close()
        self.open()

    def send_and_recieve(self, command):
        self.write(command)
        return self.read()

    def read(self):
        s=''
        try:
            s = self.tcp.read()
        except:
            print('First reading attempt failed on "{}", trying again...'.format(type(self).__name__))
            try:
                s = self.tcp.read()
            except:
                print('Timeout while reading from "{}"!'.format(type(self).__name__))
                raise
        s = s.replace('\r', '')
        s = s.replace('\n', '')
        return s
        
    def write(self, command):
        command=command+'\r\n'
        try:
            self.tcp.write(command)
            time.sleep(0.004)
        except:
            self.reconnect()
            try:
                self.tcp.write(command)
                time.sleep(0.004)
            except:
                print('Timeout while writing to "{}"!'.format(type(self).__name__))
                raise
                
                
    def AskQuestion_thread(self):
        while True:
            if self.check_connection_warning==True:
                self.check_connection_warning=False
                root = tk.Tk()
                root.withdraw()
                MsgBox = tkMessageBox.showinfo ('Warning!','can not connect to device',icon = 'warning')
                root.destroy()
            time.sleep(1)
    #----- PROTECTED REGION END -----#	//	HMP4040.programmer_methods

class HMP4040Class(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(HMP4040.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	HMP4040.global_class_variables


    #    Class Properties
    class_property_list = {
        'host':
            [PyTango.DevString, 
             '',
            ["192.168.3.215"] ],
        'port':
            [PyTango.DevLong, 
             '',
            [5025]],
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'CH1_V':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'CH1_C':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'CH2_V':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'CH2_C':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'CH3_V':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'CH3_C':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'CH4_V':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'CH4_C':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.WRITE]],
        'output_on_off':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.WRITE]],
        'output_CH1':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'output_CH2':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'output_CH3':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'output_CH4':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.WRITE],
            {
                'Memorized':"true"
            } ],
        'CH1_V_read':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'CH1_C_read':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'CH2_V_read':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'CH2_C_read':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'CH3_V_read':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'CH3_C_read':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'CH4_V_read':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'CH4_C_read':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'output_on_off_read':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ]],
        'output_CH1_read':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ]],
        'output_CH2_read':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ]],
        'output_CH3_read':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ]],
        'output_CH4_read':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(HMP4040Class, HMP4040, 'HMP4040')
        #----- PROTECTED REGION ID(HMP4040.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	HMP4040.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
